#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Feb 10 16:01:28 CST 2024
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim uart_led_behav -key {Behavioral:sim_1:Functional:uart_led} -tclbatch uart_led.tcl -protoinst "protoinst_files/system.protoinst" -log simulate.log"
xsim uart_led_behav -key {Behavioral:sim_1:Functional:uart_led} -tclbatch uart_led.tcl -protoinst "protoinst_files/system.protoinst" -log simulate.log

