# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab2/uart_led_pins_pynq.xdc

# XDC: imports/lab2/uart_led_timing_pynq.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_uart_led_0_0/system_uart_led_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_uart_led_0_0 || ORIG_REF_NAME==system_uart_led_0_0} -quiet] -quiet

# XDC: /home/rrr/XP/xup_fpga/lab2/lab2.gen/sources_1/bd/system/system_ooc.xdc
